### ISSUE TITLE
New Test Data Inventory issues, 5/1/2020 version

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#155] opened 2020-05-05 16:19 UTC
@dburgstrom We've identified a couple of issues with inventory.

- Number of units is greater than the number of beds 
![image-20200505-115015](https://user-images.githubusercontent.com/20728145/81089237-f7bd7b80-8eb0-11ea-9d47-bfc38500027c.png)

- Household type is Children only, includes designated beds not allowed in Children Only households 
![image-20200505-122420](https://user-images.githubusercontent.com/20728145/81089647-74e8f080-8eb1-11ea-9d35-cd3241cc2e6b.png)
![image-20200505-130658](https://user-images.githubusercontent.com/20728145/81089695-8205df80-8eb1-11ea-9db4-725af9e2c961.png)

**Comment by dburgstrom** [comment] 2020-05-05 16:29
Thank you for noting these. I do not see the inventory records in the first bullet in the 5/1 version. I see a total of 5 inventory records, 4083323, 4083326, 4083328, 4083329, and 4717088, same with your screenshot on the second bullet.

For the second bullet, I had fixed the issue on the user end but did not notice that the export gave the wrong HouseholdType value. I will fix that shortly.

Thanks.

**Comment by dburgstrom** [comment] 2020-05-05 18:58
Follow up to define "shortly." The issue is fixed on our end now but I want to coordinate the next update with Molly and Jules given other potential changes in the code due to outstanding issues. It will at least be updated this week, hopefully in the next couple of days.

**Comment by michelleogburn** [comment] 2020-05-05 20:15
@dburgstrom , I've also been reminded we should only use CH designated beds with project type 3. Both of the projects in second bullet are RRH. 

As for the units problem, I'm looking at the latest file and see it in the latest version. Here is the zipped file. It is the last two rows in the inventory file.
[FY 2020 HMIS CSV Data 2020_04_30 (2).zip](https://github.com/HMIS/LSASampleCode/files/4583410/FY.2020.HMIS.CSV.Data.2020_04_30.2.zip)

**Comment by michelleogburn** [comment] 2020-05-21 17:14
Resolved in later test kits.

**Closed as completed** 2020-05-21 17:14 UTC
