### ISSUE TITLE
Flag 780 - Possible Issue with 8.17

### ISSUE THREAD

**Issue by jbloescw** [abtassociates/LSASampleCode#616] opened 2020-11-05 22:00 UTC
We are seeing some ProgramIDs come through for LSA Calculated, row 57, that are NOT in the Project.csv.  The specs state that there must be a matching project record in but there is no join to enforce this rule.
![image](https://user-images.githubusercontent.com/44415627/98300619-25c66a00-1f7f-11eb-9f86-9edf2e9bda2e.png)

The program coming through is excluded from being added to project.csv due to its operating end date being before the report begin date.  
In the code for section 8.17, cohort 1 is performed using a left join thus allowing the project to survive from tlsa_Enrollment.  It however has no dates to count thus resulting in a 0 for the value column.

Should there be a join to lsa_project to enforce this or does this flag need to be evaluated?

**Comment by eanders** [comment] 2020-11-13 18:31
@MollyMcEvilley, can you confirm you have a fix for this going up?  I believe we talked about it yesterday on the office hours call.  If so, when can we expect that?

**Comment by KAdlerCW** [comment] 2020-11-17 22:06
We found that this issue is also triggering instances of flag ID 711. There is a set up issue in our test data set where the Project does not have a CoC code, preventing it from making it into LSA_Project, but the ProjectID is still making it into the LSACalculated. The inner join would prevent that project from being included in LSACalculated.

**Comment by michelleogburn** [comment] 2020-11-18 22:12
We found an issue with this flag, but from a different angle. 

Here is an example of the scenario

- ProjectID = 23 has Operation End Date = 01/31/2018, before FY 2019
- ProjectID = 23 is counted for lsa_Calculated.ReportRow = 59 because it matches the logic in the spec (section 8.19):

-- CohortStart = [ReportEnd - 3 Years] + 1 day, CohortEnd = Report End
-- AND OperatingEndDate is between CohortStart and CohortEnd
-- AND ExitDate > OperatingEndDate

![image-20201118-103849](https://user-images.githubusercontent.com/20728145/99594352-eef14a80-29a7-11eb-9df0-e67bb4f596b0.png)

So this is either an issue with the flag or the spec and sample code.

**Comment by MollyMcEvilley** [comment] 2020-11-23 20:51
(This is also relevant to #620)
> Should there be a join to lsa_project to enforce this or does this flag need to be evaluated?

The sample code didn't specify that the counts for 8.17 and 8.18 should be limited to active enrollments.  I've added "WHERE n.Active = 1" to the SQL there -- and there **SHOULD** be a record in lsa_Project for all of the ProjectIDs associated with active enrollments.  (commit forthcoming)

HOWEVER, if there is an EnrollmentCoC record that matches ReportCoC and the project is missing a ProjectCoC record for ReportCoC:
1. The enrollment will (appropriately) be designated an active enrollment and used for LSAPerson/Household/Calculated.
2. The project will be excluded from Project.csv.
3.  The flag will be triggered.

A join to lsa_Project would prevent the flag, but it would also result in under-counting with no way to correct the problem.  I think that the best resolution is to leave the flag in place so that the CoC has to correct the PDDE data by adding a ProjectCoC record.  
Thoughts?

**Comment by eanders** [comment] 2020-11-23 20:55
I agree, if the Project is missing a ProjectCoC in the CoC of the EnrollmentCoC, that's a project descriptor issue, but if it's getting pulled in because it wasn't active, that sounds like a bug.  Thanks for fixing, and clarifying.

**Comment by nataliesus** [comment] 2020-12-08 11:48
Hi @MollyMcEvilley 
Should "_OperatingEndDate If not NULL, date must be >= ReportStart_" be included in the "Logic" section for both Systemwide LSA and Project-Focused LSA? Such an important restriction is included only in the relevant data table description.
![image](https://user-images.githubusercontent.com/28144855/101480060-d26b8100-395b-11eb-8128-9ce4cd93b676.png)

As Michelle said, the report uses Cohort = 20 for lsa_Calculated.ReportRow = 59 so Projects active within 3 years but ended before [report end date] are also included.

At the same time, these projects are not included in Projects.csv because of "_OperatingEndDate If not NULL, date must be >= ReportStart_" restriction.

As a result, we receive flag 780.

Please advise.

**Comment by nataliesus** [comment] 2020-12-10 11:59
Hi @MollyMcEvilley , 

We also have flag 781 that is similar to flag 780. Please advise.

Interestingly, flag 780 is a "vendor flag", but flag 781 is a "CoC flag".

**Comment by cwanska** [comment] 2020-12-17 17:50
Investigate PA-600

**Comment by MichelleNevius** [comment] 2020-12-22 20:05
FYI:  NJ-500 and NJ-501, both Foothold customers, also are getting flag 780.  Posting here as per request in vendor call.

**Comment by MichelleNevius** [comment] 2020-12-30 14:35
Question: should we ask our customers to extend the Operating Dates by one day to have them extend into the date range captured by the LSA? This would be inaccurate, but we could ask them to do it in order to generate proper LSA data.

**Comment by jessejorstad** [comment] 2020-12-31 15:16
Thank you all for your patience.

We have confirmed that there are instances where the flag is identifying a ProjectID in LSACalculated.csv and then searching for that ProjectID in Project.csv, even though the sample code excludes that ProjectID from Project.csv (because the project ended prior to ReportStart). The team will review this issue and adjust accordingly for next year. 

For this year, if the ProjectID that is triggering the flag is only seen in a row in LSACalculated for cohort 20 communities should submit a note to their data liaison through email confirming that the project is closed and there are no outstanding enrollments. The liaison will retain that note for the usability review. Note: if the ProjectID triggering the flag has enrollments in cohort 1 then this explanation will not be accepted as LSACalculated is reporting there were active records during the reporting period.

**Closed as completed** 2020-12-31 15:20 UTC

**Comment by MollyMcEvilley** [comment] 2021-08-05 22:21
FY2021 specs include all projects active on or after 10/1/2012, which should resolve the issue of ProjectIDs in LSACalculated that are not in Project.csv.
