### ISSUE TITLE
Flag 528

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#656] opened 2021-01-25 15:44 UTC
Well, this is a new one for us... And it is very possibly a rare scenario among Bitfocus customers.

Here are Household details:
![image-20210125-103822](https://user-images.githubusercontent.com/20728145/105728333-e275fa80-5ee0-11eb-9ee6-c8ab2d730a6e.png)

![image-20210125-103421](https://user-images.githubusercontent.com/20728145/105728378-f02b8000-5ee0-11eb-93bd-2a4a44c91c54.png)

According to the spec and sample code, `ex.HHAdultAge = 25` because of `MaxAge = 37`

![image-20210125-104229](https://user-images.githubusercontent.com/20728145/105728507-14875c80-5ee1-11eb-82ab-2a643c2bd66b.png)

Thus, this Households has **HHAdultAge = 25 AND HHType = 3** in tlsa_Exit that caused Flag 528.

So either it is LSA sample code/spec issue or Flag issue that cause Flag 528.

**Comment by nataliesus** [comment] 2021-01-27 12:13
Hi @MollyMcEvilley , @jessejorstad, @cwanska ,
Could you please advise how flag 528 can be resolved? Thank you!

**Comment by MollyMcEvilley** [comment] 2021-06-04 13:55
Note to self:  The adult exited before the start of the report period and shouldn't be included in the calculation.

Specs and sample code should be updated so that:

- _3.4 HMIS Client Enrollments_ adds a column to tlsa_Enrollment called **ExitCohort**
- _7.2 Select Reportable Exits_ includes setting tlsa_Enrollment.**ExitCohort** only for enrollments with exits in the relevant cohort period  
_7.4 Set Population Identifiers for Exit Cohort Households_ excludes enrollments for household members who exited prior to the report period (based on tlsa_Enrollment.**ExitCohort**).

**Comment by MollyMcEvilley** [comment] 2021-08-05 21:58
The issue is addressed in section _7.9 Set Population Identifiers for Exit Cohort Households_ of FY2021 specs by limiting population identifiers to enrollments where ExitDate > CohortStart.

**Closed as completed** 2021-08-06 19:47 UTC
